---
- name: Install Terraform and Git
  hosts: all
  become: yes
  tasks:
    - name: Update the package manager
      apt:
        update_cache: yes
    - name: Install Git
      apt:
        name: git
        state: present
    - name: Ensure the necessary packages are installed (for Ubuntu/Debian systems)
      apt:
        name:
          - unzip
          - wget
        state: present
      become: yes
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        dest: /tmp/terraform.zip
    - name: Unzip Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
    - name: Ensure Terraform binary is executable
      file:
        path: /usr/local/bin/terraform
    - name: GIT repository is cloned
      git:
        repo: https://github.com/rakesh300pt/Rakesh_Terraform.git
        dest: /home/azureuser/demo
        version: main
        update: yes
    - name: Initialize Terraform working directory
      community.general.terraform:
        project_path: /home/azureuser
        state: present
    - name: Plan Terraform changes
      ansible.builtin.command:
        cmd: terraform plan -out=tfplan
        chdir: /home/azureuser
    - name: Validate Terraform configuration
      ansible.builtin.command:
        cmd: terraform validate
      args:
        chdir: /home/azureuser
    - name: Apply Terraform changes
      ansible.builtin.command:
        cmd: terraform apply -auto-approve
      args:
        chdir: /home/azureuser
    - name: Remove cloned repositories
      file:
        path: /home/azureuser/demo
        state: absent
    - name: Remove specific created files
      file:
        path: /home/azureuser/test.tf
        state: absent
~

